# This is a basic workflow to help you get started with Actions

name: CICD-EKS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set env
        run: | 
          echo "DATE=$(date +%y-%m-%d-%H)" >> $GITHUB_ENV
          echo "DATE2=$(date +%y-%m-%d)" >> $GITHUB_ENV
      
      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: chmod gradle
        run: chmod -X ./gradlew
        
      - name: build
        run: gradle build
        
      - name: build check
        run: ls ./build/libs   
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: copy war
        run: cp ./build/libs/*.war ./Dockerfile/*.war 
        
      - name: docker build
        run: |
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:eks_tomcat_github_ver${{ env.DATE2 }} ./Dockerfile
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:eks_tomcat_github_latest ./Dockerfile
         docker images
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:eks_tomcat_github_ver${{ env.DATE2 }}
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:eks_tomcat_github_latest
         
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: was-deploy restart
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout restart deployment/tomcat-was

        
      - name: change file name
        run: mv ./build/libs/*.war ./build/libs/${{ env.DATE }}.war

      - name: upload backup file to s3  
        uses: prewk/s3-cp-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: ./build/libs
          dest: s3://${{ secrets.AWS_BUCKET }}/backup/{{ env.DATE2 }}.war
          flags: --recursive

      
        

          
